version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspaces/ongmanager-backend:cached
    # Mantém o container rodando para o VS Code / Codespaces se conectar
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: service:postgres # O container app usará a rede dos serviços para facilitar conexão localhost
    depends_on:
      - postgres
      - rabbitmq
      - redis

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ongmanager
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: devuser
      RABBITMQ_DEFAULT_PASS: devpassword
    ports:
      - "5672:5672"   # Porta do protocolo AMQP
      - "15672:15672" # Painel de controle Web (Management UI)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  rabbitmq-data:
  redis-data: